import StoreProvider from "@/lib/redux";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={"min-h-screen bg-background font-sans antialiased"}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
